# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_of_question',
            name='Image_of_Question',
            field=models.ImageField(blank=True, default=None, upload_to=b''),
        ),
    ]
