# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.DateTimeField(verbose_name='Data publikacji'),
        ),
    ]
