# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180501_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Answer_To_Question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Name_of_Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='Text_of_Answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='name_of_question',
            name='Text_of_Question',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
