# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180219_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='number_question',
            field=models.CharField(default='Pytanie nr:', max_length=200),
        ),
    ]
