# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180501_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Who_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('How_Many', models.IntegerField(default=0)),
                ('Who_Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Who_Answer',
        ),
    ]
