# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180501_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='who_answer',
            name='Where_Answer',
            field=models.ManyToManyField(default=None, to='polls.Name_of_Question'),
        ),
    ]
